<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_purus_dealers"
 *
 * Auto generated by Extension Builder 2014-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pxa Dealers',
	'description' => 'Pxa Dealers',
	'category' => 'plugin',
	'author' => 'Andriy Oprysko',
	'author_email' => 'andriy@pixelant.se',
	'author_company' => 'Pixelant',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'realurl' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>