<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_dealers"
 *
 * Auto generated by Extension Builder 2014-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Pxa Dealers',
    'description' => 'Extension to display searchable dealers/shops or other points of interests on Google maps',
    'category' => 'plugin',
    'author' => 'Andriy Oprysko',
    'author_email' => 'andriy@pixelant.se',
    'author_company' => 'Pixelant',
    'state' => 'stable',
    'uploadfolder' => '0',
    'clearCacheOnLoad' => 1,
    'version' => '3.3.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'static_info_tables' => ''
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
