<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_dealers"
 *
 * Auto generated by Extension Builder 2014-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Pxa Dealers',
    'description' => 'Display dealers on a map',
    'category' => 'plugin',
    'author' => 'Andriy Oprysko',
    'author_email' => 'andriy@pixelant.se',
    'author_company' => 'Pixelant',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.99.99',
            'static_info_tables' => ''
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
